sudo: required

services:
- docker

language: generic

install:
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- export PATH=$PATH:$HOME/.cargo/bin
- cargo install cross

script:
- cross build --target=armv7-unknown-linux-gnueabihf
